env:
  global:
    - CC_TEST_REPORTER_ID=0cd70ec2eae2a0def96ffaa2b654cd8ab92249fb1c92396deb0cc2ca7bd6452a
language: ruby
rvm: 2.6.7
cache: bundler
services: postgresql
before_script:
  - gem update --system
  - gem install bundler
  - bundle exec bundle install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake db:create db:schema:load
  - bundle exec rake spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT