default: &default
  adapter: postgresql
  encoding: unicode
  host: 0.0.0.0
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: rails_roadmap_development

test:
  <<: *default
  database: rails_roadmap_test